name: Static Analysis and Coding Standards

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analysis-and-cs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: xhprof

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-8.4-composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run CS
        run: composer cs

      - name: Run SA
        run: composer sa

      - name: Run PHP Mess Detector
        run: ./vendor/bin/phpmd src text ./phpmd.xml

      - name: Download ComposerRequireChecker PHAR
        run: |
          curl -L https://github.com/maglnet/ComposerRequireChecker/releases/latest/download/composer-require-checker.phar -o composer-require-checker.phar
          chmod +x composer-require-checker.phar

      - name: Run composer-require-checker without config
        run: ./composer-require-checker.phar check ./composer.json
